server {
    listen 80;
    server_name localhost;

    # Убедимся, что MIME-типы подгружаются правильно
    include /etc/nginx/mime.types;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        
        # Разрешаем доступ всем User-Agent
        limit_except GET POST {
            deny all;
        }
    }

    # Явная настройка для картинок и мета-данных
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf|txt)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
        # Снимаем возможные ограничения на уровне location
        allow all;
    }

    # Обработка robots.txt
    location = /robots.txt {
        root /usr/share/nginx/html;
        allow all;
        access_log off;
        log_not_found off;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
